blog_demo/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, HiddenField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Titill', validators=[DataRequired(message='Insláttar krafist')])
    content = TextAreaField('Efni', validators=[DataRequired(message='Insláttar krafist')])
    fldh = HiddenField('FieldHidden')
    orient = HiddenField('OrientHidden')
    submit = SubmitField('Skrá')

blog_demo/games_pgn/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint, json)
from flask_login import current_user, login_required
from blog_demo import db
from blog_demo.models import Game
from blog_demo.games_pgn.forms import ImportPgnForm
from blog_demo.games_pgn.utils import save_pgn

games_pgn = Blueprint('games_pgn', __name__)


@games_pgn.route('/skak/<int:game_id>')
def skak(game_id):
    pgn = Game.query.get_or_404(game_id)
    pgn_string = pgn.pgn
    pgnlist = pgn_string.split('\n')
    return render_template('skak.html', title='skak', pgnlist=json.dumps(pgnlist))


@games_pgn.route("/pgnimport", methods=['GET', 'POST'])
@login_required
def pgnimport():
    form = ImportPgnForm()
    picture_path = url_for('static', filename='profile_pics/'+current_user.image_file)
    if form.validate_on_submit():
        if form.importpgn.data:
            texti = save_pgn(form.importpgn.data)
            flash('Flutningur tókst '+texti, 'success')
        #     debug = form.importpgn.data
        # db.session.commit()
        # flash(picture_path, 'success')
        return redirect(url_for('games_pgn.pgnimport'))
    # elif request.method == 'GET':
    #     form.username.data = current_user.username
    #     form.email.data = current_user.email
    # image_file = url_for('static', filename='profile_pics/'+current_user.image_file)
    return render_template('import_pgn.html', title='Pgn import', image_file=picture_path, form=form)


@games_pgn.route('/games', methods=['GET', 'POST'])
def games_list():
    if request.method == 'POST':
        search_str = request.form['search_str']
        # flash('leitar strengurinn er post '+search_str, 'success')
    else:
        search_str = request.args.get('search_str', "")
        # flash('leitar strengurinn er GET '+search_str, 'success')
    page = request.args.get('page', 1, type=int)
    if search_str == "":
        games = Game.query.order_by(Game.date_posted.desc(),  Game.white).paginate(page=page, per_page=12)
    else:
        games = Game.query.order_by(Game.white).filter(
            Game.white.ilike('%'+search_str+'%') | Game.black.ilike('%'+search_str+'%') | Game.event.ilike('%'+search_str+'%')).paginate(page=page, per_page=12)
    return render_template('games.html', games=games)


@games_pgn.route('/game/<int:game_id>/delete', methods=['POST'])
@login_required
def delete_game(game_id):
    game = Game.query.get_or_404(game_id)
    if game.sendandi != current_user:
        abort(403)
    db.session.delete(game)
    db.session.commit()
    flash('Skákinni hefur verið eytt', 'success')
    return redirect(url_for('games_pgn.games_list'))


@games_pgn.route('/chess_setup')
def chess_setup():
    return render_template('chess_setup.html', title='skak_setjaupp')

blog_demo/main/routes.py
from flask import render_template, request, Blueprint
from blog_demo.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='about')

blog_demo/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from blog_demo import db
from blog_demo.models import Post
from blog_demo.posts.forms import PostForm


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    default_str = ''
    fen_str = request.args.get('fen_str', default_str)
    orient_str = request.args.get('orient_str', default_str)
    hvitur_str = request.args.get('hvitur_str', default_str)
    svartur_str = request.args.get('svartur_str', default_str)
    result_str = request.args.get('result_str', default_str)

    if fen_str == '':
        form = PostForm()
    else:
        if orient_str == '':
            orient_str = 'white'
        if hvitur_str == '':
            form = PostForm(request.values,  fldh=fen_str, orient=orient_str)
        else:
            form = PostForm(request.values, title=hvitur_str+'-'+svartur_str+' '+result_str, fldh=fen_str, orient=orient_str)
    if request.method == 'POST' and form.validate():

        #    if form.validate_on_submit():
        post = Post(title=form.title.data, fen1=form.fldh.data, orientation=orient_str, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Bloggið hefur verið skráð', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='Nýtt blogg', form=form, legend="Nýtt blogg")


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Bloggið hefur verið uppfært', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.fldh.data = post.fen1
        form.orient.data = post.orientation
    return render_template('create_post.html', title='Uppfæra  blogg', form=form, legend="Upfæra blogg")


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user and not current_user.admin:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('your post has been deleted', 'success')
    return redirect(url_for('main.home'))

blog_demo/users/routes.py
from flask import (render_template, url_for, flash, redirect, request, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from blog_demo import db, bcrypt
from blog_demo.models import User, Post
from blog_demo.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, RequestResetForm, ResetPaawordForm)
from blog_demo.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,  password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created You are now able to log in !", "success")
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/'+current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(
        Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('A email has been sent to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Reset Password', form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPaawordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated. You are now able to log in !", "success")
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Password', form=form)

blog_demo/templates/about.html
{% extends "layout.html"%}
{% block content%}
<article class="media content-section">
    <div class="media-body">
    <div class="article-metadata">

    <h5>skakir.net</h5>
    <p class="article-content">
        Jæja enn ein skák vefsíðan gætu sumir hugsað. Ég hef verið innilokaður í sjálfskipaðri sóttkví og fannst tilvalið að búa til einfalda skáksíðu þar sem hægt er að skoða telfdar skákir. Hægt er fyrir hvern sem er að hlaða inn skákum. Til þess þarf að skrá sig, Þegar búið er að skrá sig er einnig hægt að blogga um stöður sem koma fyrir í skákunum. Einnig er hægt að setja upp stöður og blogga um þær. Hægt er að pastea fen strengi í edit boxið og setja upp stöðu. Ég hafði ekki hugsað mér að þetta yrði notað sem skákbanki. Heldur hafði ég hugsað þetta sem grunnur fyrir innanlands skákir sem telfdar eru hjá skákfélugum og umfjöllun um þær. Einnig er hægt að setja inn skákþrautir. Hægt er að blogga um skákir frá sjónarhorni svarts. Þá þarf að flippa stöðunni áður en bloggað er um stöðuna.
    </p>
</div>
</div>
</article>
{% endblock content%}

blog_demo/templates/chess_setup.html
{% extends "layout.html"%}
{% block content%}
<script type="text/javascript" src='/static/js/jquery-3.4.1.min.js'></script>
<script type="text/javascript" src='/static/js/chessboard-1.0.0.js'></script>
<script type="text/javascript" src='/static/js/json3.min.js'></script>
<script type="text/javascript" src='/static/js/chess.js'></script>
<div id="board" style="width: 350px"></div>
<div style"margin: 5px auto; width: 400px;>
    <button type="button" id="Flippa" class="btn btn-outline-info mt-3">Flippa</button>
    <button id="startBtn" class="btn btn-outline-info mt-3">Byrjunarstaða</button>
    <button id="clearBtn" class="btn btn-outline-info mt-3">Hreinsa borð</button>
    <button id="setupBtn" class="btn btn-outline-info mt-3">Setja upp</button>
   <form action="{{url_for('posts.new_post')}}" method="get" id="form_skak">
        <p><input type="text" name="fen_str" id="fen_strengur" class="form-control"></p>
        <input type="hidden" name="orient_str" id="orient_strengur">
        {% if current_user.is_authenticated %}
            <input type="submit" class="btn btn-outline-info mt-3" value="Blogga um stöðu">
        {% endif %}
    </form>
</div>
<script>
var init = function() {
    var config = {
            pieceTheme: '/static/img/chesspieces/wikipedia/{piece}.png',
            draggable: true,
            dropOffBoard: 'trash',
            sparePieces: true,
            onChange: onChange
            }


var game = new Chess();

var board = new ChessBoard('board',config);
var $fen = $('#fen')
function onChange (oldPos, newPos) {
   $('#fen_strengur').val(Chessboard.objToFen(newPos));
}


$('#startBtn').on('click', board.start)

$('#setupBtn').on('click', function() {
    var setup_str = $('#fen_strengur').val();
    console.log(setup_str);
    board.position(setup_str);
});

$('#clearBtn').on('click', board.clear);

$('#Flippa').on('click',function() {
        board.flip();
        console.log(board.orientation());
        $('#orient_strengur').val(board.orientation());
    });

    }; // end init()
    $(document).ready(init);
    </script>
    {% endblock content%}

blog_demo/templates/games.html
{% extends "layout.html"%}
{% block content%}
<div class="content-section">
    <form action={{url_for('games_pgn.games_list')}} method="get">
    <div class="input-group input-group-sm mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-sm"><button class="btn btn-outline-info btn-sm" type="submit">Leita</button></span>
  </div>
  <input type="text" name="search_str" id="LeitaId" class="form-control" size="30" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm" value="{{ request.form['search_str'] if request.method=='POST' else request.args.get('search_str', "")}}">
  </form>
</div>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Hvítur</th>
          <th scope="col">Svartur</th>
          <th scope="col">Mót</th>
          <th scope="col">Úrslit</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
          {% for game in games.items %}
          <tr>
            <td>{{game.white}}</td>
            <td>{{game.black}}</td>
            <td>{{game.event[0:15]}}</td>
            <td>{{game.result}}</td>
            <td>
                <a class="btn btn-secondary btn-sm" href="{{url_for('games_pgn.skak',game_id=game.id)}}">Skoða</a>
                {%if game.sendandi == current_user %}
                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal{{game.id}}">Eyða</button>
                {%endif%}
            </td>
          </tr>
          {%if game.sendandi == current_user or current_user.admin %}
          <!-- Modal -->
          <div class="modal fade" id="deleteModal{{game.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Á að eyða skákinni?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action={{url_for('games_pgn.delete_game', game_id=game.id)}} method="post">
                      <input class="btn btn-danger" type="submit" value="Delete">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                  </form>
                </div>
              </div>
            </div>
          </div>
          {%endif%}

          {% endfor %}
      </tbody>
    </table>
    </div>
    {% for page_num in games.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2)%}
       {% if page_num %}
          {%if games.page == page_num%}
            <a class="btn btn-info mb-4" href="{{url_for('games_pgn.games_list', page=page_num,search_str=request.form['search_str'] if request.method=='POST' else request.args.get('search_str', "")) }}">{{ page_num }}</a>
         {%else%}
         <a class="btn btn-outline-info mb-4" href="{{url_for('games_pgn.games_list', page=page_num,search_str=request.form['search_str'] if request.method=='POST' else request.args.get('search_str', ""))}}">{{ page_num }}</a>
         {% endif %}
       {%else%}
         ---
       {% endif %}
    {% endfor %}

 {% endblock content%}

blog_demo/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <base href="../" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/chessboard-1.0.0.min.css') }}">
    <!-- <link rel="stylesheet" href="{{url_for('static',filename='style.css')}}"> -->

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Skákir</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse"  id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{url_for('main.home')}}">Heim</a>
                <a class="nav-item nav-link" href="{{url_for('main.about')}}">Um Skákir</a>
                <a class="nav-item nav-link" href="{{url_for('games_pgn.games_list')}}">Skákir</a>
                <a class="nav-item nav-link" href="{{url_for('games_pgn.chess_setup')}}">Stilla upp</a>
              </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated%}
                <a class="nav-item nav-link" href="{{url_for('games_pgn.pgnimport')}}">Hlaða inn skákum</a>                <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">Nýtt Blogg</a>
                <a class="nav-item nav-link" href="{{url_for('users.account')}}">Reikningur</a>
                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Skrá út</a>
                {%else%}
              <a class="nav-item nav-link" href="{{url_for('users.login')}}">Skrá inn</a>
              <a class="nav-item nav-link" href="{{url_for('users.register')}}">Skráning</a>
              {%endif%}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
          <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                      {% if messages %}
                        {% for category, message in messages %}
                          <div class="alert alert-{{ category }}">
                            {{ message }}
                          </div>
                        {% endfor %}
                      {% endif %}
                    {% endwith %}
                    {% block content %}{% endblock %}
                  </div>
                  <div class="col-md-4">
          <div class="content-section">
            <!-- <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like. -->
            <ul class="list-group">
                <li class="list-group-item list-group-item-light">
                <img src="{{url_for('static',filename='images/taflmenn.jpeg')}}" alt="Bobby Fischer" class="rounded mx-auto d-block img-thumbnail"></li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script type="text/javascript" src='/static/js/jquery-3.4.1.min.js'></script>
    <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog_demo/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Skrá inn</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{url_for('users.reset_request')}}">Gleymt lykilorð?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Þarftu reikning? <a class="ml-2" href="{{ url_for('users.register') }}">Skráðu þig núna</a>
        </small>
    </div>
{% endblock content %}

blog_demo/templates/post.html
{% extends "layout.html" %}
{% block content%}
{%if post.fen1%}
<script type="text/javascript" src='/static/js/jquery-3.4.1.min.js'></script>
<script type="text/javascript" src='/static/js/chessboard-1.0.0.js'></script>
<script type="text/javascript" src='/static/js/json3.min.js'></script>
<script type="text/javascript" src='/static/js/chess.js'></script>
{%endif%}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',
  filename='profile_pics/'+post.author.image_file)}}" alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
      {% if post.author == current_user or current_user.admin%}
      <div>
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{url_for('posts.update_post',post_id= post.id)}}">Uppfæra</a>
          <button type="button" class="btn btn-danger btn-sm m1" data-toggle="modal" data-target="#deleteModal">Eyða</button>
      </div>
      {% endif %}
    </div>
    <h4 class="article-title">{{ post.title }}</h4>
    {%if post.fen1%}
       <div id="board1" style="width: 200px" class="mb-3 mr-3"></div>
    {%endif%}
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form action={{url_for('posts.delete_post', post_id=post.id)}} method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{%if post.fen1%}
<script>
    var init = function() {
        var config = {
            pieceTheme: '/static/img/chesspieces/wikipedia/{piece}.png',
            position: '{{post.fen1}}',
            orientation: '{{post.orientation}}',
            draggable: true
            }
        var board1 = Chessboard('board1', config);
}; // end init()
$(document).ready(init);
</script>
{%endif%}
{% endblock content%}

blog_demo/templates/user_posts.html
{% extends "layout.html" %}
{% block content%}
<h5 class="mb-3">Posts by {{user.username}} ({{posts.total}})</h5>
{% for post in posts.items %}
<article class="media content-section">
  <img class="rounded-circle article-img" src="{{url_for('static',
  filename='profile_pics/'+post.author.image_file)}}" alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{{url_for('users.user_posts',username=post.author.username)}}">{{ post.author.username }}</a>
      <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
    </div>
    <h4><a class="article-title" href="{{url_for('posts.post', post_id=post.id)}}">{{ post.title }}</a></h4>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1,right_current=2)%}
   {% if page_num %}
      {%if posts.page == page_num%}
        <a class="btn btn-info mb-4" href="{{url_for('users.user_posts',username=user.username, page=page_num)}}">{{ page_num }}</a>
     {%else%}
     <a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{ page_num }}</a>
     {% endif %}
   {%else%}
     ---
   {% endif %}
{% endfor %}
{% endblock content%}